### ISSUE TITLE
Location should not be hardcoded for templates

### ISSUE THREAD

**Issue by torivara** [sam-cogan/arm-ttk-extension#26]
After the pipeline task automatically updated from 1.0.7 to 1.0.8 I am seeing test fails for "Location should not be hardcoded". I have "hardcoded" the location parameter with [resourcegroup().location], and am unsure as to whether this really can be considered as hardcoded.

Should I change my practice, or is this something that can be added as an exception?

Also, I would like to prevent automatic extension version updates, but maybe this is an Azure DevOps issue? Is there a way to explicitly request 1.0.7 instead of 1.0.8 of the extension?

**Comment by sam-cogan** [comment]
What is your template name that shows this error?

The reason I ask is that this test has two scenarios, if your testing a top level template then you should use resourcegroup.location as a default value for the location parameter, and any child templates should have the value passed in from the top level template, not using resourcegroup.locaiton.

The problem is that the TTK team made a decision that all top level templates need to be named azuredeploy.json or maintemplate.json. If it is not named this then it assumes it is a child template and will fail this test. I don't really like this decision, most of my top level templates are named something different, but that is how the test works currently. To resolve this you either need to rename your top level template to match, or use the skip parameter to skip the test.

You can pin an extension in Azure DevOps, but I think you can only do it to major version, not minor. I will have to check.

**Comment by torivara** [comment]
I think the redefinition of child vs main template could be the issue here. I am not using nested templates at the moment, and have not opted for azuredeploy.json as template names.

Could maybe consider moving these to their own folders and renaming to azuredeploy.json. It would require some more work with my modular approach, but I'm sure this is a step towards a more clean module structure. Good to know that there was a change in the TTK logic, and not necessarily the templates themselves.

I kind of went for the quick workaround atm, and skip the location tests for now. Thank you for your reply. I guess you can consider this issue resolved.

**Comment by pim-simons** [comment]
It is now possible to specify a specific filename with the MainTemplateFile parameter, see: [https://github.com/Azure/arm-ttk/pull/261](https://github.com/Azure/arm-ttk/pull/261).

I am using many different templates with specific names that do not use nesting, so as a workaround I have skipped the "Location should not be hardcoded" test. Would be nice if we can specify a MainTemplateFile, or maybe a flag to indicate that all templates should be processed as a MainTemplateFile (in case you are using wildcards (*.json) and all templates should be handled as the MainTemplateFile)?
